import numpy as np
import torch
from torch_geometric.data import Data
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

"""
Graph construction utilities and dataset splitting helpers.

This module is dataset-agnostic. It only assumes:
    * a pandas DataFrame,
    * numeric feature columns,
    * a binary {0, 1} label column,
    * one or more "relation" columns used to form same-value cliques
      (e.g. card_id, user_id, device_id).

Edge topology: Star (not full mesh).
    Groups with more than max_group_size nodes are sampled down before
    building the star, so RAM usage stays bounded.

Paper splits supported (Sec 4.1):
    supervised      -> 0.40 / 0.20 / 0.40
    semi-supervised -> 0.01 / 0.10 / 0.89
"""


# ---------------------------------------------------------------------------
# Edge construction
# ---------------------------------------------------------------------------


def _group_indices_by_value(values):
    """
    =======================
    Group row indices by value
    =======================
    For every distinct entry in `values`, collect the list of row
    indices that share this entry.

    Args:
        values: array-like of length N.
    Returns:
        dict[value -> list[int]]
    """
    groups = {}
    for i, v in enumerate(values):
        groups.setdefault(v, []).append(i)
    return groups


def _star_edges_from_group(idxs, max_group_size):
    """
    =======================
    Star edges inside one group
    =======================
    Connects the first node (center) to every other node (leaves),
    both directions. Groups larger than max_group_size are sampled
    down before building the star to keep RAM bounded.

    Complexity: O(n) edges instead of O(n^2) for full mesh.

    Args:
        idxs           : list of node indices sharing the same relation value.
        max_group_size : int, cap before sampling.
    Returns:
        list of [src, dst] pairs (both directions present).
    """
    if len(idxs) < 2:
        return []

    if len(idxs) > max_group_size:
        import random
        idxs = random.sample(idxs, max_group_size)

    center = idxs[0]
    edges = []
    for other in idxs[1:]:
        edges.append([center, other])
        edges.append([other, center])
    return edges


def build_edges_from_column(values, max_group_size=500):
    """
    =======================
    Star edges from one relation column
    =======================
    Union of star topologies over all groups defined by identical values.
    Returns a list of [src, dst] pairs (both directions present).

    Args:
        values         : array-like of relation column values.
        max_group_size : int, passed down to _star_edges_from_group.
    """
    groups = _group_indices_by_value(values)
    edges = []
    for idxs in groups.values():
        edges.extend(_star_edges_from_group(idxs, max_group_size))
    return edges


def _edges_list_to_tensor(edges):
    """
    =======================
    List-of-edges -> edge_index tensor
    =======================
    Args:
        edges: list of [src, dst] pairs (may be empty).
    Returns:
        LongTensor of shape [2, E].
    """
    if len(edges) == 0:
        return torch.zeros((2, 0), dtype=torch.long)
    return torch.tensor(edges, dtype=torch.long).t().contiguous()


def build_edge_index(df, relation_cols, max_group_size=500):
    """
    =======================
    Build edge_index from multiple relation columns
    =======================
    Unions star edges generated by each relation column present in
    `df`. Missing columns are silently skipped.

    Args:
        df             : pandas DataFrame.
        relation_cols  : list of column names.
        max_group_size : int, cap per group before star is built.
    """
    edges = []
    for col in relation_cols:
        if col in df.columns:
            edges += build_edges_from_column(df[col].values, max_group_size)
    return _edges_list_to_tensor(edges)


# ---------------------------------------------------------------------------
# Feature and label extraction
# ---------------------------------------------------------------------------


def _extract_features(df, feature_cols, scale):
    """
    =======================
    Extract node feature matrix
    =======================
    Casts the selected columns to float32 and optionally applies
    StandardScaler (recommended when feature scales differ widely).

    Returns:
        FloatTensor of shape [N, F].
    """
    feats = df[feature_cols].values.astype(np.float32)
    if scale:
        feats = StandardScaler().fit_transform(feats).astype(np.float32)
    return torch.from_numpy(feats)


def _extract_labels(df, label_col):
    """
    =======================
    Extract binary label vector
    =======================
    Returns:
        LongTensor of shape [N] with values in {0, 1}.
    """
    return torch.tensor(df[label_col].values, dtype=torch.long)


# ---------------------------------------------------------------------------
# Public graph builder
# ---------------------------------------------------------------------------


def build_graph(df, feature_cols, label_col, relation_cols=None, scale=True,
                max_group_size=500):
    """
    =======================
    Build a torch_geometric Data from a DataFrame
    =======================
    Args:
        df             : pandas DataFrame.
        feature_cols   : list of numeric feature column names.
        label_col      : binary {0, 1} label column name.
        relation_cols  : list of relation column names used to form
                         same-value stars. Defaults to ["card_id"].
        scale          : whether to apply StandardScaler to features.
        max_group_size : int, groups larger than this are sampled down
                         before building the star topology.
    Returns:
        torch_geometric.data.Data with x, edge_index, y.
    """
    if relation_cols is None:
        relation_cols = ["card_id"]

    x          = _extract_features(df, feature_cols, scale)
    y          = _extract_labels(df, label_col)
    edge_index = build_edge_index(df, relation_cols, max_group_size)

    return Data(x=x, edge_index=edge_index, y=y)


# ---------------------------------------------------------------------------
# Train / val / test splits
# ---------------------------------------------------------------------------


def _make_bool_mask(n, indices):
    """
    =======================
    Build a boolean mask of length N
    =======================
    Returns a BoolTensor of length `n` with True at positions `indices`.
    """
    mask = torch.zeros(n, dtype=torch.bool)
    mask[indices] = True
    return mask


def _can_stratify(y):
    """Stratify chỉ khả thi khi mọi class hiện diện đều có >= 2 samples.
    Tránh ValueError 'least populated class has only 1 member' của sklearn."""
    if y is None or len(y) < 2:
        return False
    counts = np.bincount(np.asarray(y))
    nonzero = counts[counts > 0]
    return len(nonzero) > 0 and nonzero.min() >= 2


def _split_train_rest(idx, y, train_ratio, seed):
    """
    =======================
    First cut: train vs (val + test)
    =======================
    Stratified split khi class counts cho phép, fallback non-stratified
    khi data mất cân bằng cực đoan (1 class có < 2 samples).
    """
    if _can_stratify(y):
        return train_test_split(
            idx, y, train_size=train_ratio, random_state=seed, stratify=y
        )
    print(
        "[graph_utils] WARN: stratify không khả thi (class có <2 samples), "
        "fallback non-stratified split cho train_rest"
    )
    return train_test_split(
        idx, y, train_size=train_ratio, random_state=seed
    )


def _split_val_test(pool_idx, pool_y, rel_val_ratio, seed):
    """
    =======================
    Second cut: val vs test (from remaining pool)
    =======================
    Stratified split khi pool_y cho phép, fallback non-stratified
    khi data quá nhỏ / mất cân bằng.
    """
    if _can_stratify(pool_y):
        return train_test_split(
            pool_idx,
            train_size=rel_val_ratio,
            random_state=seed,
            stratify=pool_y,
        )
    print(
        "[graph_utils] WARN: stratify không khả thi (pool_y có <2 samples mỗi class), "
        "fallback non-stratified split cho val_test"
    )
    return train_test_split(
        pool_idx,
        train_size=rel_val_ratio,
        random_state=seed,
    )


def add_splits(data, train_ratio=0.4, val_ratio=0.2, seed=42):
    """
    =======================
    Attach stratified train/val/test masks in place
    =======================
    Writes `data.train_mask / val_mask / test_mask`. Stratification
    by `data.y` keeps class ratios consistent across splits.

    Recipes:
        supervised      -> train_ratio=0.4,  val_ratio=0.2
        semi-supervised -> train_ratio=0.01, val_ratio=0.10
    """
    n = data.num_nodes
    y = data.y.cpu().numpy()
    idx = np.arange(n)

    test_ratio = 1.0 - train_ratio - val_ratio
    assert test_ratio > 0, "train_ratio + val_ratio must be < 1"

    train_idx, temp_idx, _, y_temp = _split_train_rest(idx, y, train_ratio, seed)

    rel_val_ratio = val_ratio / (val_ratio + test_ratio)
    val_idx, test_idx = _split_val_test(temp_idx, y_temp, rel_val_ratio, seed)

    data.train_mask = _make_bool_mask(n, train_idx)
    data.val_mask   = _make_bool_mask(n, val_idx)
    data.test_mask  = _make_bool_mask(n, test_idx)
    return data